name: Docker Layer Caching
description: Cache images created between main run and post run

branding:
  icon: layers
  color: blue

inputs:
  key:
    description: An explicit key for restoring and saving the cache
    required: true
    default: docker-layer-caching-${{ github.workflow }}-{hash}
  restore-keys:
    description: An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    required: false
    default: docker-layer-caching-${{ github.workflow }}-
  concurrency:
    description: The number of concurrency when restoring and saving layers
    required: true
    default: '4'
  skip-save:
    description: Skip saving layers in the post step
    required: false
    default: 'false'

runs:
  using: node16
  main: main.ts
  post: post.ts
